### ISSUE TITLE
GetUserId method returns email instead of numeric userId

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/ala-auth-plugin#23]
AuthService.getUserId() returns email instead of numeric userId.

<img width="1792" alt="Screen Shot 2022-05-24 at 12 36 54 pm" src="https://user-images.githubusercontent.com/72474143/169937348-a81acbbe-aabc-4ab4-ae1f-757a88634889.png">

**Comment by sughics** [comment]
Issue has been resolved as of 5.1.0 SNAPSHOT
