### ISSUE TITLE
When viewing user list filtered by role, the paging buttons do not include the role

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-auth-plugin#6]
When viewing the user list by role, such as the following: 

https://auth.ala.org.au/userdetails/admin/userRole/list?role=ROLE_APPD_USER

the role is not included in the paging buttons. 

This results in using the paging buttons going to the full list, rather than the filtered list.

**Comment by ansell** [comment]
The role is now included in the paging buttons, but the link is not pointing to the right location.

It now points to:

https://auth.ala.org.au/userdetails/ws/admin/userRole/list?role=ROLE_APPD_USER&max=100&offset=100

instead of:

https://auth.ala.org.au/userdetails/admin/userRole/list?role=ROLE_APPD_USER&max=100&offset=100

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/userdetails#50
