### ISSUE TITLE
Upgrade cas-client-core dependency

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-auth-plugin#7]
The cas-client-core dependency that is being used, 3.1.12, is from 2010, and numerous versions have been released since then that we should explore using, considering this is a security sensitive dependency:

https://search.maven.org/#search|gav|1|g%3A%22org.jasig.cas.client%22%20AND%20a%3A%22cas-client-core%22

**Comment by sbearcsiro** [comment]
Commits 6a66c27 and c1d2d74 address this issue.
